name: Publish Package

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build || echo "No build script (ignoring)"
      
      - name: Publish
        run: |
          pnpm config set "//registry.npmjs.org/:_authToken" "${NODE_AUTH_TOKEN}"
          
          if [[ $GITHUB_REF == *"-beta"* ]]; then
            pnpm publish --tag beta --no-git-checks
          else
            pnpm publish --no-git-checks
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      